---
- name: Check for backports repository
  ansible.builtin.shell: grep -E '^deb.*backports' /etc/apt/sources.list
  register: backports_repository
  ignore_errors: yes

- name: Remove backports repository if it exists
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items: "{{ backports_repository.stdout_lines }}"
  when: backports_repository.rc == 0
