---
- hosts: all
  become: true
  tasks:
    - name: Remove universe from sources list
      ansible.builtin.apt_repository:
        repo: "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_facts['lsb']['codename'] }} universe"
        state: absent
    
    - name: Remove universe (update) from sources list
      ansible.builtin.apt_repository:
        repo: "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_facts['lsb']['codename'] }}-updates universe"
        state: absent

    - name: Remove universe (security) from sources list
      ansible.builtin.apt_repository:
        repo: "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_facts['lsb']['codename'] }}-security universe"
        state: absent

    - name: Remove multiverse from sources list
      ansible.builtin.apt_repository:
        repo: "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_facts['lsb']['codename'] }} multiverse"
        state: absent
    
    - name: Remove multiverse (update) from sources list
      ansible.builtin.apt_repository:
        repo: "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_facts['lsb']['codename'] }}-updates multiverse"
        state: absent

    - name: Remove multiverse (security) from sources list
      ansible.builtin.apt_repository:
        repo: "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_facts['lsb']['codename'] }}-security multiverse"
        state: absent

    - name: Remove backports from sources list
      ansible.builtin.apt_repository:
        repo: "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_facts['lsb']['codename'] }}-backports main restricted universe multiverse"
        state: absent