---
- name: Create an app user and add to Docker group
  hosts: all
  become: true

  vars:
    username: app
    authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCphXPfWwdneWALBz5Z4BTOQOcF7eIO4qdIDdjA21Z0nMiFlUg5t2V7qy8vKLxeoSSAx/e+cUflgMc77d0+8HFU6L5jF97cise0uEX/TN4JV4ouiolRniYUaC4TmU4VA5FVlQWcYCRnnsuECG/uppHt8s5emCBRhxvfy9zTQUqBrj27QUh/3YtVvaTKebSz//3PNrao0q7RwN4vRK85Rj3d56Ggt0ZGpFPLOuInMBSrFd6UHsj4k3ymaxiuwOK2NZ7RiuMJsC0RiaIhR6jtT+oM0AUpfUj9q6Y+HYH+Mhuz7/vXbVqS/qLm0/Dsc94Obu43KunV2TH3Uebyosl7qiaRBeIhUnImwl7J0GhJvF4jSH1AWx4JW/zWRatypxSyttdgf1tMR1WadBGymglWqdKQ8Ojvcd2mLpjV6Trr6OMtWE36C5CXUb1zbV9WQ7sA2LPV3wGXojG/SWT1s5kshwKucaUCtgu9t2CG80tIwDMj23fGlI4f9dJDYZfJISwXELdo8W6V3Hayj9mr/ByChW1AFoWWWnOHoLNF5+OSRBzLCbyZfCJSzbiSysFMOrU6ZlBsx8lDsffWIPdH3hplxzrYF5IzuCSBqAI06nfCZ0AZW1pBEx6wMMebI/7/qJM5o3Wi87LQm2aJjgls4GT1cZ7/mQ+L8vLmQ/+4QwZ2RLa7pBWCqfmu6JnjlgO05tqrSDMmUSlJwW3dX3O1rXM9wfBhRCSoazyCt/qGC+JBQAV9ohpNMLZsgPewDj+G/TeeyDQIPEFgt5geoj5XgjY+s5lU5MiTzfn0o8OQheTX6I0c3rvXcGyzdJTkg2ELTDiE+5sV5yalL67OeapNoQLb9zxq+yIor8Qz19nVCMbPkP1tz9efiV1+CLdmxrRFi7xZX+wAS9YnIMLbJiHf67ptmsDCG8yQPikHYaGV9Xe5ibRV6zbTGmZDCF2B6Q0nZmv2EZkDboHIojATtedetoX1O7WBzVtf0Bp/hqaSVHDVZoLOQytlGjFHAjc9L2YZ+v2kv6KNr17dvtk6EblzffgIgNSUbnTo6/Sukn2h/PkQCIn4fVK8ut0pZqZK9Sd3y7YtIZFnOwf4mxt6tajcbjDL3OhtlSBxmsho+Cq6v1Gnu20HQocryVugcEwk7w9t/7KaS7LoccSsFT8D18n28ZQ56c9A+xmuKmgVKMQOGaFW2soWze2M71QjR4Mx4oH/B+dTDoP5Yb+EH5OlPBTRS87QtmlsyE7HA3PlSUJc6puw6u9lLHxBVMMWkhcnVgcY13ZABYx/O5ZIYCfyiy9ooLQhKcK2l8cH4e/CmRtABPPiYisrp0mf1mwX+faIbqcR40zb17ANR2Z+PXQA8ITZFXrBXwBf dev+app@pazl.dev

  tasks:
    - name: Create group
      group:
        name: "{{ username }}"
        state: present

    - name: Create user
      user:
        name: "{{ username }}"
        group: "{{ username }}"
        groups: docker
        shell: /bin/bash
        state: present
        append: true

    - name: Generate a random password
      ansible.builtin.set_fact:
        password: "09162bfe90b27d8a243760a9a848d99329f5c61d31eea466ac9ff7e31c93eb29"

    - name: Change user password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Add authorized keys
      authorized_key:
        user: "{{ username }}"
        key: "{{ item }}"
      loop: "{{ authorized_keys }}"

    - name: Check if SSH key already exists
      stat:
        path: /home/{{ username }}/.ssh/id_rsa
      register: ssh_key_stat

    - name: Generate SSH key
      openssh_keypair:
        path: /home/{{ username }}/.ssh/id_rsa
        size: 8192
      when: not ssh_key_stat.stat.exists
