---
- hosts: webservers
  tasks:

    - name: Update apt cache and install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Enable nginx
      service:
        name: nginx
        enabled: yes

    - name: Copy the default configuration
      copy:
        src: ../templates/nginx/default
        dest: /etc/nginx/sites-enabled/default

    - name: Copy options-ssl-nginx.conf
      copy:
        src: ../templates/nginx/options-ssl-nginx.conf
        dest: /etc/nginx/options-ssl-nginx.conf

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
