---
- name: Install MySQL using Docker
  hosts: all
  become: yes

  vars:
    image_name: mysql
    image_tag: 8.2.0
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Pull MySQL Docker Image
      docker_image:
        name: "{{ image_name }}"
        source: pull
        tag: "{{ image_tag }}"

    - name: Run MySQL Container
      docker_container:
        name: mysql_container
        image: "{{ image_name }}:{{ image_tag }}"
        env:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        restart_policy: always
