---
- name: Create an app user and add to Docker group
  hosts: all
  become: true

  vars:
    username: app
    authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCm9Jh4SBAJfal8yKaebOqrWtiro12nt9Od7P2HuR9bxxmFIyHrXRO0yFqUJrtxo+HbaX1/MSTzSYfkbJIEFoPtNybDNUexInVNjIyBU6EmrPvIWXddODt/ndFqCF1i4M1mVKNI5NS531FjXjodVnppE/C1Cv/LAkc5DGTfqFvDYgW2i4T6UAoXZM7LOtSzYWNg3aU547/vkCmVkigLulIPTiw85ULtrLf7t6gVlAu+cRCXtxmw+bsbldJpdmFPWizA2ugYW3CWL+n7sSFG++z31saseNF0ws/r4CKoH2y4WH9dyRW7YZXkT3EELWUlMp3E9g37i7cxwpdg6WF1nZf0RZwJ1c/LD0AyhGIjyuJQS+u4EBPvEwgKbkrBkznPcfwWIum2xKrTem3+LgKc1xcG8APWPF3zyWEciUlFIPzS6K1jbv6NepNGpkolJYdRbhR2PVygT1VOyiFRe/BMjCYXapNnf405a3CH25HYKI1uHoQczq1Z4YcrUcLVxuG8tAnyna2WjTKSczKyIDrlOhrHepjRoLlk8CXRkwb1hF++g2vvKt3e6iM0x+Q4Lty5XSOm2wjvgZZhrzUbMwcz1QfYohn7SmJAyxWK/jH+zkbx7iC3DdBT46kFdTdnZi0gqNe2k+gw29HMNkG35o45/mmWVaB4L/GXesunZWx8ckOsMYb2lU6KILbk7snbKPUPLbzQLE3LorT+xRcZAw3IP+VByyMQdF+5xRJiDg1QxqEsjOMR6GDDRy4dUXuozwX5AFY/klmNpeS+YU5coPPLDPI91H+3hEOXHxV/MG3JX5Mw3VrVX6JyvypF07qkgkM6AgpPXTgfMb1i+S6hg16sPOYVmxCfkgJIwYQzFqueRKUHuS1t6+/QmgiI1OnYjekW7IiLQrdoCtUPbb8R2ZvN2DRtrjApqaKVJUNtFtCkTLTINvQGtdKi0xXUkuNsL4z1kLhbZco9XgGM6J+GpJmfl69cO+v57L27iXIrcCwhTvAQd1LSWDUxxKHw3CNTJM2VZEtk4W4QgVqWGdEw7k2f+lucaZc+aB2V5m5VGi9Eh7TVLzTO+/CCAqru13ZBT4zsqFQL0xnVa1tC2NhO/I9Qb+DMJHu13cZM7/XudnYKARyj01elKHVUQz/hqtr9++VBajH4vsvWQbQZ2U+DyO2MEDMeBMC7XF2GxNrHon2Y04MtdTBq8VbFRWEi0r6IRucC9kesepehiNGwZ1nhu0GVDyb/L7csZY9qPaE4+rC8OFjJ4Yh7WQ31l8B67Czg9eGsnXULXjCWRgpO8W/qgsYzcfoHD07QsC8O5PMJoA0fiSFszdAasWpBWMVgjgm7yBeH2V4nzoPtUVxpGuA4MTqjCI1H dev+password@pazl.dev

  tasks:
    - name: Create group
      group:
        name: "{{ username }}"
        state: present

    - name: Create user
      user:
        name: "{{ username }}"
        group: "{{ username }}"
        groups: docker
        shell: /bin/bash
        state: present
        append: true

    - name: Add authorized keys
      authorized_key:
        user: "{{ username }}"
        key: "{{ item }}"
      loop: "{{ authorized_keys }}"
