---
- name: Install Nginx and configure SSL certificates with Certbot
  hosts: all
  become: true

  vars:
    nginx_sites:
      - server_name: pazl.dev
        admin_email: dev@pazl.dev
        apps:
          - location: /password
            proxy: http://127.0.0.1:8000
          - name: /prayer
            proxy: http://127.0.0.1:8002
          - name: /
            proxy: http://127.0.0.1:8004

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: true

    - name: Install Certbot
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Schedule automatic renewal of SSL certificates with Certbot
      cron:
        name: "Renew Certbot SSL certificates"
        minute: "0"
        hour: "12"
        job: "certbot renew --quiet"
        user: root
        state: present

    - name: Setup virtualhosts
      include_tasks: nginx/virtual_host.yaml
      loop: "{{ nginx_sites }}"
      loop_control:
        loop_var: nginx_site

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
