---
- name: Remove backports repository from Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Get domain name from sources.list file
      shell: "grep '^deb.*-backports' /etc/apt/sources.list"
      changed_when: false
      register: repository

    - name: Remove backports repository
      apt_repository:
        repo: "{{ repository.stdout }}"
        state: absent
        filename: backports
