---
- name: Setup database server
  hosts: db
  become: true

  vars:
    ubuntu_codename: "{{ ansible_distribution_release | lower }}"

  tasks:
    - include_tasks: chapter/remove-backport-repository.yaml
    - include_tasks: chapter/install-docker.yaml
    - include_tasks: chapter/install-postgresql.yaml
