---
- name: Setup application server
  hosts: news
  become: true

  vars:
    ubuntu_codename: "{{ ansible_distribution_release | lower }}"

  tasks:
    - include_tasks: chapter/remove-backport-repository.yaml

    - include_tasks: chapter/install-docker.yaml
