- name: Create nginx template
  template:
    src: ../../templates/nginx/nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ parent_item.host }}.conf

- name: Create application directory
  file:
    path: "/home/{{ parent_item.username }}/{{ parent_item.root_dir }}/.well-known/acme-challenge"
    state: directory
    recurse: true
    owner: "{{ parent_item.username }}"
    group: "{{ parent_item.username }}"
    mode: "0755"

- name: Copy docker-compose file
  template:
    src: "../../templates/{{ parent_item.username }}/{{ parent_item.root_dir }}/docker-compose.yml.j2"
    dest: "/home/{{ parent_item.username }}/{{ parent_item.root_dir }}/docker-compose.yml"
    owner: "{{ parent_item.username }}"
    group: "{{ parent_item.username }}"
    mode: '0644'

- name: Start application services
  community.docker.docker_compose:
    project_src: "/home/{{ parent_item.username }}/{{ parent_item.root_dir }}"
    state: present
    pull: true
    remove_orphans: true
  vars:
    ansible_python_interpreter: /bin/python3
