- name: Create a group for the user
  group:
    name: "{{ parent_item.username }}"
    state: present

- name: Create the user
  user:
    name: "{{ parent_item.username }}"
    state: present
    group: "{{ parent_item.username }}"

- name: Create .ssh folder
  file:
    path: "/home/{{ parent_item.username }}/.ssh"
    state: directory
    owner: "{{ parent_item.username }}"
    group: "{{ parent_item.username }}"
    mode: "0755"

- name: Create authorized_keys file
  file:
    path: "/home/{{ parent_item.username }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ parent_item.username }}"
    group: "{{ parent_item.username }}"
    mode: "0600"

- name: Copy authorized_keys
  copy:
    content: "{{ parent_item.authorized_keys | join('\n') }}"
    dest: "/home/{{ parent_item.username }}/.ssh/authorized_keys"

- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "/home/{{ parent_item.username }}/.ssh/id_rsa"
    size: 8192
    type: rsa

- name: Change owner and group of generated private keys
  file:
    path: "/home/{{ parent_item.username }}/.ssh/id_rsa"
    owner: "{{ parent_item.username }}"
    group: "{{ parent_item.username }}"

- name: Change owner and group of generated public keys
  file:
    path: "/home/{{ parent_item.username }}/.ssh/id_rsa.pub"
    owner: "{{ parent_item.username }}"
    group: "{{ parent_item.username }}"
