name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Setup
    permissions: read-all
    steps:
      - name: Configuring ssh
        run: |
          eval `ssh-agent -s`
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cd ~/.ssh/
          pwd
          ls -lah
          ssh-keyscan -p $SSH_PORT -H $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.NEWS_LB_HOST }}
          SSH_PORT: ${{ secrets.VM_SSH_PORT }}
      - uses: actions/checkout@v4
      - name: Run ansible
        run: |
          service ssh status
          ansible-playbook -vvv -i inventory.yml \
          --private-key ~/.ssh/id_rsa playbook/deploy-application.yaml \
          -e "DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }}" \
          -e "DOCKER_TAG=${{ github.event.inputs.tag }}" \
          -e "SPRING_DATASOURCE_URL=${{ vars.SPRING_DATASOURCE_URL }}" \
          -e "SPRING_DATASOURCE_USERNAME=${{ vars.DB_USERNAME }}" \
          -e "SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}"
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
