name: Setup Database Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - name: Configuring ssh
        run: |
          eval `ssh-agent -s`
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cd ~/.ssh/
          pwd
          ls -lah
          ssh-keyscan -p $SSH_PORT -H $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.NEWS_LB_HOST }}
          SSH_PORT: ${{ secrets.VM_SSH_PORT }}
      - uses: actions/checkout@v4
      - name: Run ansible
        run: |
          service ssh status
          ansible-playbook -vvv -i inventory.yml --private-key ~/.ssh/id_rsa playbook/setup-database-server.yaml -e "postgres_password=$DB_PASSWORD"
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ANSIBLE_HOST_KEY_CHECKING: false
